include:
  - project: "papers/papers-internal/internal"
    file: "/.base-gitlab-ci.yml"

stages:
  - build
  - test
  # - publish

build:
  stage: build
  script:
    - docker build -t $GOOGLE_TAG .
  
test:
  stage: test
  before_script:
    - docker rm -f unit-$CI_COMMIT_SHA || true
  script:
    - docker run --name unit-$CI_COMMIT_SHA $GOOGLE_TAG
  after_script:
    - docker rm -f unit-$CI_COMMIT_SHA || true